const config = {
    TEMPERATURE_LIMIT : 3,
    RAINFALL_LIMIT : 2,
    HUMIDITY_LIMIT : 1,
    AIR_POLLUTION_LIMIT : 1,
    CO2_EMISSIONS_LIMIT : 5,

    TEMPERATURE_MIN_THRESHOLD : -9,
    TEMPERATURE_MAX_THRESHOLD : 30,
};

export default config;